sudo: required
language: php
php:
- '7.2'
before_script:
- cd ./creational/abstract-factory/php
- composer self-update
- composer install
- composer dump-autoload -o
script:
- ./vendor/bin/phpunit -c "./phpunit.xml"
deploy:
  edge: true
  provider: bluemixcloudfoundry
  username: eclesiomelo.1@gmail.com
  organization: sampleorg
  space: staging
  manifest: manifest.yml
  password:
    secure: BJNgYLLDachZoCxhxTE/mznPpn3O1aKURBpCUeL9JknkZKKaXkMafQB4yL2cnw/KQfwDnHoExntsIFjwVCHGa/W6yNE2B+mm71aABRAV/ibUGRcD45k568u82o2PJie23iwTFjQJS8tfUEToRNPZVmCQ0+KAe08zB6ycOTJg8nnC099vHr0/HxKtg6HyIKK8Q5f9GJ9F3xGmoQ1S9yXMghsieAHv7nFT97ZsBwHtWhVS7inDRnUFWWsKUH+5gLQLoR1FdhRcwyHJR/kBDC8A0DftFaYzsPD3vUL5y4DmQ0TDFhmDr8At+ROHYVZztOAc/FVakFKncrfzRVojfNi/dhEw/0p9kL/pmXZCI+akYQchSDoQ4PSBZeKxcfY/QcvkgeejBg3NdaVgNEHq7/axZgioFRaJeVfB93KiglJAQOtU1TRsxnAKN2Dz4jaC6OEv6r+z0Wvm6tZ4mWqaQX8vyIMsYSgseuBBkTIqJCOTrn6aedWTth8Zrq+KVx56T/Tc1ke+uJlAN//bsIrX43FG0Kb3iOl9FqjiHxsYpcH0TM94URQQIhfa1W034LX6oVmA6sCQSJxRdoZ63CbFKDyMOuoL+C6zK8/EMmEP7Y+5KudJngIBm2WDgWCIZMic/6PCv0oBEQKM2PBtvMI5ztGECXq5kWRSerQw1TSeARdjaMg=
