sudo: required
language: php
php:
  - '7.1'
  - '7.2'
before_script:
  - cd ./creation/abstract-factory/php
  - composer self-update
  - composer install
script:
  - ./vendor/bin/phpunit -c "./phpunit.xml"