sudo: required
language: php
php:
- '7.2'
before_script:
- cd ./creational/abstract-factory/php
- composer self-update
- composer install
- composer dump-autoload -o
script:
- ./vendor/bin/phpunit -c "./phpunit.xml"
deploy:
  provider: bluemixcloudfoundry
  manifest: manifest.yml
  username: $BLUEMIX_USER
  password: $BLUEMIX_PASSWORD
  organization: $BLUEMIX_ORGANIZATION
  space: $BLUEMIX_SPACE
